---
- name: install confd files
  include_role:
    name: confd-files-1.1.0

- name: copy binaries
  copy:
    src: "{{ role_path }}/files/opt/app/current/"
    dest: /opt/app/current/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: set up k8s env
  copy:
    dest: /opt/app/current/bin/envs/confd.env
    content: |
      APISERVER_LB_FILE=/data/appctl/data/apiserver-lb
      KUBE_CONFIG=/data/kubernetes/admin.conf

- name: install net-tools
  apt:
    name: [ 'net-tools' ]
    state: present
    update_cache: yes
      

- name: prepare upgrade snapshot
  vars:
    snapshot_sources:
    - /opt/app
    - /opt/k8s-client
    - /opt/helm
    - /opt/jq
    - /opt/yq
    # - /root/.helm
    - /root/.config
    - /root/.cache
    # 初始化的 helm 暂时没有 ~/.local 路径，做 migrate 时添加上
    - /root/.local
  include_role:
    name: app-upgrade
