---
- name: install packages
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: helm
      pkg_version: "{{ helm_version }}"
      pkg_url: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
      pkg_type: tgz
      extracts: true
      creates: helm
      bin_links:
      - src: helm
        dest: /usr/local/bin/helm

- name: copy configs
  copy:
    src: "{{ role_path }}/files/opt/app/"
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install helm-2to3
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: helm-2to3
      pkg_version: "{{ helm_2to3_version }}"
      dest_path: /root/.local/share/helm/plugins/helm-2to3/
      pkg_url: https://github.com/helm/helm-2to3/releases/download/v{{ helm_2to3_version }}/helm-2to3_{{ helm_2to3_version }}_linux_amd64.tar.gz
      pkg_type: tgz
      extracts: true
      extra_opts: ['--strip-components=0']
      creates: 2to3

- name: helm add repo
  shell: |
    helm repo ls | grep -o {{ helm_stable_repo }} || helm repo add stable "{{ helm_stable_repo }}"
    helm repo ls | grep -o {{ helm_main_repo }} || helm repo add main "{{ helm_main_repo }}"
    helm repo ls | grep -o {{ helm_test_repo }} || helm repo add test "{{ helm_test_repo }}"

- name: helm completion for BASH
  shell: helm completion bash > /etc/profile.d/helm-completion.sh
