---
- name: set vars
  set_fact:
    config_path: /etc/docker/daemon.json
    all_k8s_images: "{{ docker_images_k8s + docker_images_k8s_new }}"
    all_ks_images: "{{ docker_images_ks + docker_images_ks_new }}"

# private_registry_url 需要自己定义，用于镜像的拉取
- name: update docker daemon.json
  copy:
    dest: "{{ config_path }}"
    content: |
        {
            "registry-mirrors": ["{{ private_registry_url }}"],
            "exec-opts": ["native.cgroupdriver=systemd"],
            "storage-driver": "overlay2"
        }

- name: run docker server
  systemd:
    name: docker
    masked: no
    state: started
    daemon_reload: yes

- name: pull k8s images
  shell: docker pull {{ image_name }}
  loop:
    "{{ all_k8s_images }}"
  loop_control:
    loop_var: image_name

- name: pull ks images
  shell: docker pull {{ image_name }}
  loop:
    "{{ all_ks_images }}"
  loop_control:
    loop_var: image_name

- name: update docker daemon.json
  copy:
    dest: "{{ config_path }}"
    content: |
        {}

- name: run docker server
  systemd:
    name: docker
    masked: no
    state: stopped
    daemon_reload: yes
