---
- name: set vars
  set_fact:
    docker_start_cmd: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
    replace_docker_start_cmd: ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock
    docker_port: 5000
    service_path: /lib/systemd/system/docker.service
    config_path: /etc/docker/daemon.json

# private_registry_url 需要自己定义，用于镜像的拉取
- name: update docker daemon.json
  copy:
    dest: "{{ config_path }}"
    content: |
        {
            "registry-mirrors": ["{{ private_registry_url }}"],
            "exec-opts": ["native.cgroupdriver=systemd"],
            "storage-driver": "overlay2"
        }

- name: run docker server
  systemd:
    name: docker
    masked: no
    state: started
    daemon_reload: yes

- name: pull k8s images
  shell: docker pull {{ image_name }}
  loop:
    "{{ docker_images_k8s }}"
  loop_control:
    loop_var: image_name

- name: pull ks images
  shell: docker pull {{ image_name }}
  loop:
    "{{ docker_images_ks }}"
  loop_control:
    loop_var: image_name

- name: update docker daemon.json
  copy:
    dest: "{{ config_path }}"
    content: |
        {}

- name: run docker server
  systemd:
    name: docker
    masked: no
    state: stopped
    daemon_reload: yes
