---
- name: install kubectl
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: k8s-client
      pkg_version: "{{ k8s_version }}"
      pkg_url: https://dl.k8s.io/v{{ k8s_version }}/kubernetes-client-linux-amd64.tar.gz
      pkg_type: tgz
      extracts: yes
      creates: kubectl
      bin_links:
      - src: client/bin/kubectl

- name: kubectl completion bash
  shell:
    kubectl completion bash > /etc/profile.d/kubectl-completion.sh
